import JSZip from 'jszip'

export interface ExportProjectOptions {
  appName: string
  files?: Record<string, string>
  sourceCode?: string
  botToken?: string
}

export async function exportProjectToZip(options: ExportProjectOptions): Promise<void> {
  const { appName, files = {}, sourceCode = '', botToken = '' } = options
  const safeName = (appName || 'mazaika-project').toLowerCase().replace(/[^a-z0-9_-]/g, '_')
  const zip = new JSZip()

  // 1. Unified HTML with PWA meta tags
  let mainHtml = files['index.html'] || sourceCode || ''
  if (!mainHtml.includes('manifest.json')) {
    mainHtml = mainHtml.replace(
      '</head>',
      `  <link rel="manifest" href="manifest.json">\n  <meta name="theme-color" content="#07090E">\n  <script>\n    if ('serviceWorker' in navigator) {\n      window.addEventListener('load', () => navigator.serviceWorker.register('/sw.js').catch(console.error));\n    }\n  </script>\n</head>`
    )
  }
  zip.file('index.html', mainHtml)

  // 2. Extra files from Virtual File System (CSS, JS, etc.)
  for (const [fileName, content] of Object.entries(files)) {
    if (fileName !== 'index.html') {
      zip.file(fileName, content)
    }
  }

  // 3. PWA Manifest (manifest.json)
  const manifest = {
    name: appName || 'Mazaika WebApp',
    short_name: (appName || 'Mazaika').substring(0, 12),
    start_url: './index.html',
    display: 'standalone',
    background_color: '#07090E',
    theme_color: '#00D9FF',
    description: `Официальное веб-приложение ${appName || 'Mazaika AI Studio'}`,
    icons: [
      {
        src: 'https://cdn-icons-png.flaticon.com/512/9435/9435131.png',
        sizes: '192x192',
        type: 'image/png'
      },
      {
        src: 'https://cdn-icons-png.flaticon.com/512/9435/9435131.png',
        sizes: '512x512',
        type: 'image/png'
      }
    ]
  }
  zip.file('manifest.json', JSON.stringify(manifest, null, 2))

  // 4. Service Worker (sw.js)
  const swCode = `// Mazaika AI Studio - Offline Service Worker
const CACHE_NAME = '${safeName}-cache-v1';
const ASSETS_TO_CACHE = ['./', './index.html', './manifest.json'];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS_TO_CACHE))
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((cached) => cached || fetch(event.request).catch(() => caches.match('./index.html')))
  );
});
`
  zip.file('sw.js', swCode)

  // 5. Ready-to-run Telegram Bot script (bot.js)
  const botCode = `// =================================================================
// ${appName.toUpperCase()} - TELEGRAM BOT SERVER
// Generated by Mazaika AI Studio (https://mazaika.app)
// =================================================================
const { Telegraf, Markup } = require('telegraf');

const BOT_TOKEN = process.env.BOT_TOKEN || '${botToken || 'ВАШ_ТОКЕН_ИЗ_BOTFATHER'}';
const WEBAPP_URL = process.env.WEBAPP_URL || 'https://ваш-домен.vercel.app';

if (!BOT_TOKEN || BOT_TOKEN.includes('ВАШ_ТОКЕН')) {
  console.error('❌ ОШИБКА: Укажите реальный BOT_TOKEN в переменных окружения или файле bot.js!');
  console.log('Инструкция: Получите токен у @BotFather в Telegram.');
  process.exit(1);
}

const bot = new Telegraf(BOT_TOKEN);

// Команда /start
bot.start((ctx) => {
  const userName = ctx.from.first_name || 'Пользователь';
  return ctx.reply(
    \`👋 Здравствуйте, \${userName}!\\n\\nДобро пожаловать в официальный бот \${'${appName}'}.\\nНажмите кнопку ниже, чтобы открыть интерактивное приложение.\`,
    Markup.inlineKeyboard([
      [Markup.button.webApp('🚀 Открыть приложение', WEBAPP_URL)],
      [Markup.button.callback('📞 Поддержка / Оператор', 'contact_support')]
    ])
  );
});

// Обработка данных, отправленных из WebApp (sendData)
bot.on('message', async (ctx) => {
  if (ctx.message.web_app_data) {
    try {
      const data = JSON.parse(ctx.message.web_app_data.data);
      console.log('Получены данные из WebApp:', data);

      if (data.action === 'checkout' || data.cart) {
        await ctx.reply(
          \`✅ Заказ успешно оформлен!\\n\\n📦 Товаров: \${data.itemsCount || 1}\\n💰 Сумма: \${data.total || 0} сум\\n\\nНаш менеджер свяжется с вами для подтверждения доставки.\`
        );
      } else if (data.action === 'booking') {
        await ctx.reply(
          \`✅ Запись подтверждена!\\n\\nУслуга: \${data.service || 'Консультация'}\\nИмя: \${data.name || 'Клиент'}\\nТелефон: \${data.phone || 'Указан'}\\n\\nМы ждем вас!\`
        );
      } else {
        await ctx.reply(\`✅ Действие выполнено: \${data.action || 'Успешно'}\`);
      }
    } catch (e) {
      console.error('Ошибка парсинга WebApp данных:', e);
    }
  }
});

// Кнопка связи с поддержкой
bot.action('contact_support', (ctx) => {
  ctx.reply('Для связи с оператором напишите ваш вопрос прямо в этот чат или обратитесь к нашему менеджеру.');
});

bot.launch().then(() => {
  console.log('🤖 Telegram-бот успешно запущен!');
});

process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
`
  zip.file('bot.js', botCode)

  // 6. Node.js package.json for the bot
  const pkgJson = {
    name: safeName,
    version: '1.0.0',
    description: `Telegram Bot and WebApp for ${appName}`,
    main: 'bot.js',
    scripts: {
      start: 'node bot.js'
    },
    dependencies: {
      telegraf: '^4.16.3'
    }
  }
  zip.file('package.json', JSON.stringify(pkgJson, null, 2))

  // 7. README.md with clear instructions
  const readme = `# ${appName} — Проект Mazaika AI Studio

Этот архив содержит готовый к развертыванию веб-сайт, Progressive Web App (PWA) и серверного Telegram-бота.

## 🚀 Как запустить сайт (Бесплатно)
1. **Способ 1 (Локально):** Просто откройте файл \`index.html\` в любом браузере.
2. **Способ 2 (Vercel / Cloudflare / GitHub Pages):**
   - Загрузите файлы (\`index.html\`, \`manifest.json\`, \`sw.js\`) на [Vercel](https://vercel.com) или [Cloudflare Pages](https://pages.cloudflare.com) — сайт заработает по вашему бесплатному HTTPS-адресу через 30 секунд.

## 🤖 Как запустить Telegram-бота
1. Установите Node.js (версия 18 или новее).
2. В папке проекта выполните в терминале:
   \`\`\`bash
   npm install
   \`\`\`
3. Запустите бота, указав токен от @BotFather и URL вашего сайта:
   \`\`\`bash
   BOT_TOKEN="ВАШ_ТОКЕН" WEBAPP_URL="https://ваш-домен.vercel.app" node bot.js
   \`\`\`

## 📱 PWA (Установка на телефон)
Сайт поддерживает стандарт PWA: при открытии на мобильном устройстве (Safari на iOS или Chrome на Android) нажмите **«Поделиться» -> «На экран Домой»**, чтобы установить приложение без App Store / Google Play!
`
  zip.file('README.md', readme)

  // Generate ZIP blob and trigger browser download
  const blob = await zip.generateAsync({ type: 'blob' })
  const downloadUrl = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = downloadUrl
  a.download = `${safeName}_mazaika_project.zip`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(downloadUrl)
}
